java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2cf16889[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@32f813e0[Wrapped task = Thread[Thread-2771558,5,main]]] rejected from java.util.concurrent.ThreadPoolExecutor@2f3a3e1a[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2771533]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at cs451.links.FairLossLinks.send(FairLossLinks.java:52)
	at cs451.links.StubbornLinks.sendMessagesToBeSent(StubbornLinks.java:112)
	at cs451.links.StubbornLinks.lambda$new$1(StubbornLinks.java:78)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:222)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:665)
	at cs451.udp.UDPBulkSender.run(UDPBulkSender.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:267)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:850)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
	... 7 more
