java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:222)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:665)
	at cs451.udp.UDPBulkSender.run(UDPBulkSender.java:34)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:267)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:850)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
	... 7 more
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6fedf7f8[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5e8ee2ac[Wrapped task = Thread[Thread-56,9,main]]] rejected from java.util.concurrent.ThreadPoolExecutor@6f9a5dc2[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 49]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at cs451.links.FairLossLinks.send(FairLossLinks.java:65)
	at cs451.links.StubbornLinks.lambda$sendMessagesToBeSent$3(StubbornLinks.java:142)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at cs451.links.StubbornLinks.sendMessagesToBeSent(StubbornLinks.java:133)
	at cs451.links.StubbornLinks.lambda$new$2(StubbornLinks.java:111)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2d05db6[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@56a368b4[Wrapped task = Thread[Thread-57,10,main]]] rejected from java.util.concurrent.ThreadPoolExecutor@6f9a5dc2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 49]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at cs451.links.FairLossLinks.send(FairLossLinks.java:65)
	at cs451.links.StubbornLinks.lambda$sendAckMessagesToBeSent$4(StubbornLinks.java:163)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at cs451.links.StubbornLinks.sendAckMessagesToBeSent(StubbornLinks.java:157)
	at cs451.links.StubbornLinks.lambda$new$1(StubbornLinks.java:91)
	at java.base/java.lang.Thread.run(Thread.java:833)
